### ISSUE TITLE
issue with bob

### ISSUE THREAD

**Issue by PaladinFallen** [jimmyjon711/FactorioExtended-Plus-Logistics#13]
I got this error after loading the mod, I enable the other mods on the list and everything worked correctly.
[Error](https://imgur.com/tdRArDE)

Pic-To-Txt:
> Failed to load mods: the given sprite rectangle (left_top=0x0, right_bottom=64x64) is outside the actual sprite size (left_top=0x0, right_bottom=32x32). If this is being used as an icon you may need to define the icon_size property.: _ _ boblogistics _ _/graphics/icons/robots/construction-robot-1.png

**Comment by billbo99** [comment]
The bug is with "boblogistics" not "factorio extended plus"

 icon_size property.: **_ _ boblogistics _ _**/graphics/icons/robots/construction-robot-1.png

Nothing in this repo points at "boblogistics"

**Comment by PaladinFallen** [comment]
Ignore the comment from @billbo99 above me, "He just read the error and jumped to the first thing without trying to help", if anyone is having issues with the error I was getting using boblogistics and FactorioExtended Plus-Logistics, there is a simple fix.

You have to change the icon.size in four files to 32, instead of 64:
logisitic-robot.lua on lines 18 and 35
mk3_bots.lua on lines 5 and 13
roboport.lua on lines 8 and 38
construction-robot.lua on lines 18 and 35

If anyone asks why change the other files, instead of just construction-robot, it was to be for a safe measure. These small fixes have allowed me to run both together with no problems for over 4 hours with two other people on LAN with me.

**Comment by jimmyjon711** [comment]
Thanks for commenting, I will look into this more. But if you look at the base game construction-robot in demo-entities.lua line 6186 they are using icon_size of 64 instead of 32.

I will have to look more into what boblogistics is doing, he could be modifying base game items to match.

**Comment by billbo99** [comment]
@PaladinFallen .. if you look at `boblogistics_0.18.2\prototypes\entity\robots.lua` you can see at line 512, Bob is reverting the changes Wube made to use the newer HD graphics.

```
data.raw["construction-robot"]["construction-robot"].icon = "__boblogistics__/graphics/icons/robots/construction-robot-1.png"
data.raw["construction-robot"]["construction-robot"].icon_size = 32
data.raw["construction-robot"]["construction-robot"].icon_mipmaps = nil
data.raw["construction-robot"]["construction-robot"].idle = bobmods.logistics.construction_robot_idle(1)
data.raw["construction-robot"]["construction-robot"].in_motion = bobmods.logistics.construction_robot_in_motion(1)
data.raw["construction-robot"]["construction-robot"].working = bobmods.logistics.construction_robot_working(1)
data.raw["construction-robot"]["construction-robot"].shadow_idle = bobmods.logistics.construction_robot_shadow
data.raw["construction-robot"]["construction-robot"].shadow_in_motion = bobmods.logistics.construction_robot_shadow
data.raw["construction-robot"]["construction-robot"].shadow_working = bobmods.logistics.construction_robot_shadow_working
```

**Comment by PaladinFallen** [comment]
So I got a reply and well, I take it as "No, I'm not changing anything." [Bob's Reply](https://mods.factorio.com/mod/boblogistics/discussion/5e474a640d05a7000c7c14bf#post-1)
