### ISSUE TITLE
Hand mining Construction Bot MK3

### ISSUE THREAD

**Issue by LeSwede** [jimmyjon711/FactorioExtended-Plus-Logistics#14]
When you hand mine the MK3 Construction Bots, to get them in your inventory faster, they turn into Logi Bot MK3. This however does not happen to the Construction Bot MK2.

FE+ modules are the only mods installed.

**Comment by billbo99** [comment]
noted,  will be fixed in next release

**Comment by jimmyjon711** [comment]
fixed with 5037669a7fb935f51085f2447429a499cec8affb
