### ISSUE TITLE
Fails to load with sound issue in 0.18.2

### ISSUE THREAD

**Issue by NIronwolf** [jimmyjon711/FactorioExtended-Plus-Logistics#15]
Mod fails to load under v0.18.2 with the following error:

1.126 Error ModManager.cpp:1385: Failed to load mod "FactorioExtended-Plus-Logistics": __FactorioExtended-Plus-Logistics__/data.lua:3: ...-Plus-Logistics__/prototypes/entity/entity-logistics.lua:611: attempt to call global 'flying_robot_sounds' (a nil value)
stack traceback:
	...-Plus-Logistics__/prototypes/entity/entity-logistics.lua:611: in main chunk
	[C]: in function 'require'
	__FactorioExtended-Plus-Logistics__/data.lua:3: in main chunk
stack traceback:
	[C]: in function 'require'
	__FactorioExtended-Plus-Logistics__/data.lua:3: in main chunk

It looks like the sound updates to this version have broken things.

**Comment by billbo99** [comment]
investigating, will be fixed in next release

**Comment by chmodseven** [comment]
I am also seeing this issue in the Weapons pack as well.

![2020-01-30 12_08_24-Factorio 0 18 2](https://user-images.githubusercontent.com/16786687/73448708-5f67a600-4359-11ea-91ef-cda1480d623a.jpg)
