### ISSUE TITLE
Failure to load

### ISSUE THREAD

**Issue by Nick1Z2** [jimmyjon711/FactorioExtended-Plus-Logistics#18]
FactorioExtended Plus-Logistics 0.4.1
Factorio (Experimental) 0.18.4

mods:__FactorioExtended-Plus-Logistics__/data.lua:1: ...Extended-Plus-Logistics__/prototypes/entity/ __init__.lua:2: ... lus-logistics__/Prototypes/entity/construction-robot-lua:28: attempt to index field '?' (a nil Value) stack traceback:
...lus-Logistics__/prototypes/entity/construction-robot.lua:28: in main chunk
[C]: in function 'require'
...Extended-Plus-Logistics__/prototypes/entity/ __init__.lua:2: in main chunk
[C]: in function 'require'
__FactorioExtended-Plus-Logistics__/data.lua:1: in main chunk
stack traceback:
[C]: in function 'require'
...Extended-Plus-Logistics__/prototypes/entity/ __init__.lua:2: in main chunk
[C]: in function 'require'
__FactorioExtended-Plus-Logistics__/data.lua:1: in main chunk
stack traceback:
[C]: in function 'require'
__FactorioExtended-Plus-Logistics__/data.lua:1: in main chunk

![Fail to load](https://user-images.githubusercontent.com/29213335/73957451-abd95580-4906-11ea-9fd9-83bfb6eaa3d5.PNG)

**Comment by billbo99** [comment]
yup, was working in 0.18.3 .. looking into it now

**Comment by billbo99** [comment]
Seems the dev's have removed a property from construction-robot that sets the animation for when a robo is busy ".working" I can code around it for now with a test to validate it exists before trying to update it.

**Comment by Nick1Z2** [comment]
thx

**Comment by billbo99** [comment]
Klonan says it will be fixed in next release .. https://forums.factorio.com/viewtopic.php?f=30&t=80965

**Comment by billbo99** [comment]
0.18.5 has been released,  the issue with the amination set has been fixed within base game now.
