### ISSUE TITLE
Inventory size is reduced

### ISSUE THREAD

**Issue by StepKie** [jimmyjon711/FactorioExtended-Plus-Logistics#21]
- After the current patch, my inventory size is reset, causing me to drop half my stuff on the ground
- It can not be made bigger again (missing research for inventory size?!)

**Comment by billbo99** [comment]
FE+ has no inventory space research.

There was a trash-slot research,  is that what your talking about ?

**Comment by StepKie** [comment]
Then it is weird - I have no idea which other mod could be responsible
![Factorio-Mods](https://user-images.githubusercontent.com/17760200/77847775-e2717500-71bf-11ea-9553-6218bdf82b18.png)

If you are certain, feel free to close this ticket.

**Comment by jimmyjon711** [comment]
The only thing that will give you more inventory space in the mod set is upgraded power armor. Did you have updated power armor selected and now is it not there?

**Comment by StepKie** [comment]
No, I still have the Power Armor Mk3 equipped.
This is the save in case you want to check, or maybe I am taking crazy pills.

https://drive.google.com/open?id=15mZs1r5rMDPLwgCnWABkntHDnKIBKJ0a

Thanks for maintaining this mod!
