### ISSUE TITLE
having issues with big bags

### ISSUE THREAD

**Issue by JeffChilders** [jimmyjon711/FactorioExtended-Plus-Logistics#6]
I get the error "technology worker-robots-storage: Infinite research followed by level 10" 
looking at big bags evidently bob addressed the issue in his mod ref https://mods.factorio.com/mod/BigBags/discussion/5c9ecc28c6d894000cb2eeb6
not sure how the mod developers sort these issues out. 

On an aside If factorio reported mod conflicts abit more intuitively that would have been fucking awsome!!!! but why should that be a concern right? lol

**Comment by billbo99** [comment]
Is this still an issue ?
