### ISSUE TITLE
worker storage bug

### ISSUE THREAD

**Issue by killosabby** [jimmyjon711/FactorioExtended-Plus-Logistics#7]
so basically theres a bug that crashes to this error I have traced it to the logistic module of FE picture here https://imgur.com/a/0r7Ur2c

**Comment by jimmyjon711** [comment]
Do you have other mods installed? Does one of those mods have Infinite research for worker robot storage research?

**Comment by necrogami** [comment]
I'm getting the same bug in my painful modpack (installable mods available by searching necrogami's painful modpack on mods portal) but instead it said after level 5 instead of 10.

**Comment by billbo99** [comment]
Is this still an issue ?
