### ISSUE TITLE
Chests are not able to be upgraded via upgrade planner

### ISSUE THREAD

**Issue by zerocool444** [jimmyjon711/FactorioExtended-Plus-Logistics#8]
When using the upgrade planner, you cannot upgrade an active provider chest with the titanium logistic active provider chest as an example.  All 6 types of chests including the base titanium chest do not show up in the list of possible items that can be picked to upgrade.

**Comment by billbo99** [comment]
this should have been fixed with the 0.3.0 release

**Comment by billbo99** [comment]
closed
